create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  warehouse_id bigint,
  movement_type text not null,
  quantity integer not null check (quantity > 0),
  notes text,
  created_at timestamptz not null default now(),
  constraint stock_movements_type_check check (
    movement_type in ('in', 'out', 'adjustment', 'transfer')
  )
);

alter table public.stock_movements
  add column if not exists product_id bigint,
  add column if not exists warehouse_id bigint,
  add column if not exists movement_type text,
  add column if not exists quantity integer,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stock_movements_product_id_fkey'
  ) then
    alter table public.stock_movements
      add constraint stock_movements_product_id_fkey
      foreign key (product_id) references public.products(id) on delete restrict;
  end if;
end $$;

create index if not exists stock_movements_product_id_idx
  on public.stock_movements using btree (product_id);

create index if not exists stock_movements_warehouse_id_idx
  on public.stock_movements using btree (warehouse_id);

create index if not exists stock_movements_created_at_idx
  on public.stock_movements using btree (created_at desc);

alter table public.stock_movements enable row level security;

drop policy if exists "Stock movements are readable by authenticated users"
on public.stock_movements;

create policy "Stock movements are readable by authenticated users"
on public.stock_movements
for select
to authenticated
using (true);

drop policy if exists "Stock movements are writable by authenticated users"
on public.stock_movements;

create policy "Stock movements are writable by authenticated users"
on public.stock_movements
for all
to authenticated
using (true)
with check (true);
