create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null,
  category_id bigint,
  supplier_id bigint,
  brand text,
  cost_price numeric(12, 2) not null default 0 check (cost_price >= 0),
  selling_price numeric(12, 2) not null default 0 check (selling_price >= 0),
  barcode text,
  color text,
  description text,
  image_url text,
  low_stock_threshold integer not null default 0 check (low_stock_threshold >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_sku_key unique (sku)
);

create index if not exists products_name_idx on public.products using btree (name);
create index if not exists products_category_id_idx on public.products using btree (category_id);
create index if not exists products_supplier_id_idx on public.products using btree (supplier_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;

create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.products enable row level security;

drop policy if exists "Products are readable by authenticated users" on public.products;
create policy "Products are readable by authenticated users"
on public.products
for select
to authenticated
using (true);

drop policy if exists "Products are writable by authenticated users" on public.products;
create policy "Products are writable by authenticated users"
on public.products
for all
to authenticated
using (true)
with check (true);
